---
title: "p8105_hw5_yz4433"
author: "Yifei Zhao"
date: "2022-11-08"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)
library(broom)
library(rlist)
set.seed(1)
```


## Problem 2
```{r}
hddata = read.csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```

### Homecides summary
```{r}
tidydata = hddata %>% 
  mutate(city_state = paste(city,',',state))

sumdata = tidydata %>% 
  mutate(group = ifelse((disposition == 'Closed by arrest'), 'solved', 'unsolved')) %>% 
  group_by(city_state) %>% 
  summarise(
    total = sum(group == 'solved' | group == 'unsolved'  ),
    unsolved = sum(group == 'unsolved'))
```

### prop.test for Baltimore, MD
```{r}
rsbal = prop.test(sumdata[[1,3]], sumdata[[1,2]]) %>% 
  broom::tidy()
estbal = pull(rsbal, estimate)
cibal = c(pull(rsbal, conf.low), pull(rsbal, conf.high))
```

### prop.test for each city
```{r}
test_fun = function(x, y){data.frame(
  estimation = pull(broom::tidy(prop.test(x,y)), estimate),
  ci_low = pull(broom::tidy(prop.test(x,y)), conf.low),
  ci_high = pull(broom::tidy(prop.test(x,y)), conf.high))
}

listcol_df = sumdata %>% 
  mutate(testrs = map2(pull(sumdata, unsolved), pull(sumdata, total), test_fun)) %>% 
  select(-c(total, unsolved)) %>% 
  unnest(cols = testrs)
```

### estimates and CIs plot
```{r}
p = ggplot(listcol_df, aes(x = city_state, y = estimation, fill = city_state)) + 
  geom_bar(stat = "identity", color = "black", position = position_dodge()) +
  geom_errorbar(aes(ymin = ci_low, ymax = ci_high), width = .2, position = position_dodge(.9)) +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "estimates and CIs for each city")

print(p)
```

## Problem 3
### data with mean = 0
```{r}
output0 = vector("list", 5000)
for (i in 1:5000) {
  output0[[i]] = tibble(x = rnorm(30, mean = 0, sd = 5))
}
```

```{r}
paralist0 = vector("list", 5000)
pvlist0 = vector("list", 5000)
for (i in 1:5000) {
  paralist0[[i]] = pull(broom::tidy(t.test(unlist(output0[i]), mu = 0, alternative = "two.sided")), estimate)
  pvlist0[[i]] = pull(broom::tidy(t.test(unlist(output0[i]), mu = 0, alternative = "two.sided")), p.value)
}
```